name: Deploy Content to Azure Sentinel
on: 
  push:
    branches: [ main ]
    paths:
    - 'Detections/**'
    - '.github/workflows/sentinel-deploy**'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'cac-dev-rg'
      workspaceName: 'cac-dev-workspace'
      directory: '${{ github.workspace }}/Detections'
      cloudEnv: 'AzurePPE'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_59cfd77ca04c458695f1498af31270e7 }}

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_59cfd77ca04c458695f1498af31270e7 }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v1

    - name: Read deployment script
      id: deploymentScript
      uses: juliangruber/read-file-action@v1
      with:
        path: '${{ github.workspace }}/.github/workflows\azure-sentinel-deploy.ps1'
    
    - name: Deploy Analytic Rules
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ steps.deploymentScript.outputs.content }}